Add About Me and My Recent Work
esmiz-dream/Portfolio pull request #3
Opened 2023-01-20 13:48 UTC by esmiz-dream

### About Me and My Recent Work

In This Pull Request I:
- Added About Me Section
- Added My Recent Work Section
- Added Get in touch section

2023-01-20 14:06 UTC, osamaashraf6 reviewed
Hi @esmiz-dream  😊, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🆘💀

You have submitted a project, that there is a linter error in the stylelint ,so kindly try to fix this error😊

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-16 07:52 UTC, wayungi requested changes
Hi @esmiz-dream , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://user-images.githubusercontent.com/99656687/219296824-c045aae0-71a9-4a4d-b712-341b111d8518.png)

## Highlights
- [ ] Profesional README ✔️ 
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔️ 
- [ ] No merge conflicts ✔️ 
- [ ]  Correct GitHub flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [x] Your project is very good and thanks for the good work, Please let's fix this likely source of bugs in your code. Not that your header & nav tags are not closing correctly. Please match the tags 😄 
![faulty](https://user-images.githubusercontent.com/99656687/219297597-0a0a5d02-f2b4-4fd4-bc18-6eabeba4b6bd.png)

- [x] I have also noted that your mobile size is scrollable horizontally. This is caused by elements having a width wider than the device screen. Please fix this. The image below shows the issue 🤝 
![scrollable](https://user-images.githubusercontent.com/99656687/219301835-d5d080cb-4664-4022-bee8-8c283791e648.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 07:52 UTC, wayungi commented on index.html
> +                    <li><a href="https://github.com/esmiz-dream" target="_blank" rel="noopener"><img src="./images/m.png" alt="M"></a>
- [ ] Please use the correct font for the different parts of the this  `<section class="headline">`
  - h1 font is crete round
  - h2 font is roboto , please also apply the correct color ` #FFF5E1` you can confirm it in the figma template
  - p is poppins

2023-02-16 09:01 UTC, esmiz-dream commented on index.html
> +                    <li><a href="https://github.com/esmiz-dream" target="_blank" rel="noopener"><img src="./images/m.png" alt="M"></a>
thank you bro

2023-02-16 09:21 UTC, emmiiorji approved these changes
Hi @esmiz-dream, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Good Highlights✔️

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 09:21 UTC, emmiiorji commented on index.html
> +                </nav>
[Optional] I think that you may remove the network bar part of the design, it only shows it would look on a mobile device.

![image](https://user-images.githubusercontent.com/20554583/219321900-daea6d6e-3917-4354-8aaf-495758f52af8.png)

2023-02-16 11:41 UTC, Ibizugbe reviewed
Hi @esmiz-dream 👋👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses same branch for two different milestones🥲 It is a requirement that every milestone should be done on a different branch with a seperate pull request😉 kindly checkout into a new branch, open a new pull request with a descriptive header and summary🤗🤗

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-16 17:07 UTC, merged